# SPDX-FileCopyrightText: 2022 - 2025 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

services:

  nginx:
    image: orthancteam/orthanc-nginx:25.8.1
    depends_on: [orthanc, orthanc-auth-service, keycloak]
    restart: unless-stopped
    ports: ["80:80"]
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
#    ports: ["443:443"]
#    volumes:
#      - /.../crt.pem:/etc/nginx/tls/crt.pem
#      - /.../key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"
      ENABLE_HTTPS: "false"
# to use OHIF-plugin: you don't need the OHIF reverse proxy
      ENABLE_OHIF: "true"

  orthanc:
    image: orthancteam/orthanc:25.8.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./inbox-plugin.py:/scripts/inbox-plugin.py
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      # to use OHIF-plugin:  make sure to have a "OHIF" config and use "dicom-web" source
#      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc",
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableShares": true,
              "EnableAuditLogs": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "EnableOpenInOhifViewer3": true,
              // to use OHIF-plugin:  use http://localhost/orthanc/ohif/
              //"OhifViewer3PublicRoot": "http://localhost/orthanc/ohif/"
              "OhifViewer3PublicRoot": "http://localhost/ohif/"
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "ohif-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "http://localhost/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            },
            "Inbox": {
              "Enable": true,
              // set the following option to false if you don't wan't to offer access to an inbox to anonymous users
              "EnableAnonymousAccess": false,
              "Title": "Trial - XYZ",
              "IntroTextHtml": "<p>Welcome to this inbox.</p><p>First fill the form and once all fields are valid, upload your DICOM files.</p><p>Wait for the processing to complete.</p>",
              "CommitUrl": "plugins/inbox/commit",
              "FormValidationUrl": "plugins/inbox/validate-form",
              "ProcessingMonitoringUrl": "plugins/inbox/monitor-processing",
              "FormFields": [{
                  "Type" : "Text",
                  "Title": "Subject ID",
                  "Id": "SubjectId",
                  "Placeholder": "ex: SUB-253"
                }, 
                {
                  "Type" : "Choice",
                  "Title": "Visit ID",
                  "Id": "VisitId",
                  "Choices": ["T0", "T0 + 6 months", "T0 + 12 months", "T0 + 18 months", "T0 + 24 months"],
                  "Placeholder": "Select a visit"
                },
                {
                  "Type" : "MultilineText",
                  "Title": "Comments",
                  "Id": "Comments",
                  "Placeholder": "Any comments ?"
                },
                {
                  "Type" : "File",
                  "Title": "PDF form",
                  "Id": "PdfForm"
                }
              ]
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",
            // to use OHIF-plugin:  make sure to include "ohif" in the list
            "StandardConfigurations" : [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2",
              "ohif"
            ],
            "TokenHttpHeaders" : [ "api-key" ],
            "CheckedLevel": "studies",
            "ExtraPermissions": [
              ["post", "^/plugins/inbox/validate-form$", "upload|all"],
              ["post", "^/plugins/inbox/commit$", "upload|all"],
              ["post", "^/plugins/inbox/monitor-processing$", "upload|all"]
            ],
            "EnableAuditLogs": true
          },
          "PythonScript": "/scripts/inbox-plugin.py",
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          }
          // to use OHIF-plugin:  make sure to have a "OHIF" config and use "dicom-web" source
          //, "OHIF": {
          //  "DataSource": "dicom-web",
          //  "RouterBasename": "/orthanc/ohif/"
          //}
        }

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:25.8.1
    # always disable this port mapping in production !!!
    # ports: ["8000:8000"]
    # permissions can be customized in the permissions.json file
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
      - ./anonymous-profile.jsonc:/orthanc_auth_service/anonymous-profile.json
    depends_on: [keycloak]
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
#      ENABLE_KEYCLOAK_API_KEYS: "true"
#      # to enable the permissions edition UI in OE2, you need to provide a KEYCLOAK_CLIENT_SECRET
#      KEYCLOAK_CLIENT_SECRET: "change-me-I-am-a-secret-you-get-in-keycloak-logs"
      KEYCLOAK_CLIENT_SECRET: "m1FL0Y4GN9DsBK39NSwTWSjAQTnsPzGA"
      PUBLIC_ORTHANC_ROOT: "http://localhost/orthanc/"
      PUBLIC_LANDING_ROOT: "http://localhost/orthanc/ui/app/token-landing.html"
      # to use OHIF-plugin:  make sure to use http://localhost/orthanc/ohif/
      PUBLIC_OHIF_ROOT: "http://localhost/ohif/"
      ANONYMOUS_PROFILE_FILE_PATH: "/orthanc_auth_service/anonymous-profile.json"
#      PUBLIC_OHIF_ROOT: "http://localhost/orthanc/ohif/"
      USERS: |
        {
          "share-user": "change-me"
        }

  orthanc-db:
    image: postgres:14
    ports: ["5432:5432"]
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

# to use OHIF-plugin: you don't need this container
  ohif:
    image: orthancteam/ohif-v3:25.8.1
#  uncomment if you want to customize ohif configuration
#    volumes:
#      - ./ohif-app-config.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped


  keycloak:
    image: orthancteam/orthanc-keycloak:25.8.1
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      #KEYCLOAK_ADMIN: "admin"
      #KEYCLOAK_ADMIN_PASSWORD: "change-me"
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "change-me"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      # KC_HOSTNAME: "https://mydomain.com/keycloak"
    # volumes:
    #   - /home/bc/tmp:/usr/tmp

  keycloak-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db:
